ARG ALPINE_VERSION=3.21
FROM alpine:${ALPINE_VERSION}
LABEL Maintainer="Trainliang <trainliang@gmail.com>"
LABEL Description="Lightweight container with Nginx 1.26 & PHP 8.4 based on Alpine Linux."
# Setup document root
WORKDIR /var/www/html

# Install packages and remove default server definition
RUN apk add --no-cache \
    curl \
    nginx \
    php84 \
    php84-zip \
    php84-pdo_mysql \
    php84-pdo_pgsql \
    php84-mongodb \
    php84-pecl-memcache \
    php84-pecl-memcached \
    php84-bcmath \
    php84-redis \
    php84-ctype \
    php84-curl \
    php84-dom \
    php84-fileinfo \
    php84-fpm \
    php84-gd \
    php84-pdo \
    php84-intl \
    php84-mbstring \
    php84-mysqli \
    php84-opcache \
    php84-openssl \
    php84-phar \
    php84-session \
    php84-tokenizer \
    php84-xml \
    php84-xmlreader \
    php84-xmlwriter \
    supervisor

# Configure nginx - http
COPY conf/nginx.conf /etc/nginx/nginx.conf
# Configure nginx - default server
COPY conf/conf-d /etc/nginx/conf.d/

# Configure PHP-FPM
ENV PHP_INI_DIR /etc/php84
COPY conf/fpm-pool.conf ${PHP_INI_DIR}/php-fpm.d/www.conf
COPY conf/php.ini ${PHP_INI_DIR}/conf.d/custom.ini

# Configure supervisord
COPY conf/supervisord8.conf /etc/supervisor/conf.d/supervisord.conf

# Make sure files/folders needed by the processes are accessable when they run under the nobody user
RUN chown -R nobody:nobody /var/www/html /run /var/lib/nginx /var/log/nginx

# Switch to use a non-root user from here on
USER nobody

# 创建 /logs 目录并设置权限
RUN mkdir -p /logs && chown -R nobody:nobody /logs

# Add application
COPY --chown=nobody src/ /var/www/html/
COPY --chown=nobody errors/ /var/www/errors
#COPY src/ /var/www/html/
#COPY errors/ /var/www/errors
# Expose the port nginx is reachable on
EXPOSE 8080

# Let supervisord start nginx & php-fpm
CMD ["/usr/bin/supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]

# Configure a healthcheck to validate that everything is up&running
HEALTHCHECK --timeout=10s CMD curl --silent --fail http://127.0.0.1:8080/fpm-ping || exit 1