ARG ALPINE_VERSION=3.21
FROM alpine:${ALPINE_VERSION}
LABEL Maintainer="Trainliang <trainliang@gmail.com>"
LABEL Description="Lightweight container with Nginx 1.26 & PHP 7.4 based on Alpine Linux."

# Setup document root
WORKDIR /var/www/html

# Install packages and remove default server definition
RUN apk add --no-cache \
  curl \
  nginx \
  php7.4 \
  php7.4-ctype \
  php7.4-curl \
  php7.4-dom \
  php7.4-fileinfo \
  php7.4-fpm \
  php7.4-gd \
  php7.4-intl \
  php7.4-mbstring \
  php7.4-mysqli \
  php7.4-opcache \
  php7.4-openssl \
  php7.4-phar \
  php7.4-session \
  php7.4-tokenizer \
  php7.4-xml \
  php7.4-xmlreader \
  php7.4-xmlwriter \
  supervisor

# Configure nginx - http
COPY conf/nginx.conf /etc/nginx/nginx.conf
# Configure nginx - default server
COPY conf/conf.d /etc/nginx/conf.d/

# Configure PHP-FPM
ENV PHP_INI_DIR /etc/php7.4
COPY conf/fpm-pool.conf ${PHP_INI_DIR}/php-fpm.d/www.conf
COPY conf/php.ini ${PHP_INI_DIR}/conf.d/custom.ini

# Configure supervisord
COPY conf/supervisord.conf /etc/supervisor/conf.d/supervisord.conf

# Make sure files/folders needed by the processes are accessable when they run under the nobody user
RUN chown -R nobody:nobody /var/www/html /run /var/lib/nginx /var/log/nginx

# Switch to use a non-root user from here on
USER nobody

# Add application
COPY --chown=nobody src/ /var/www/html/
COPY --chown=nobody errors/ /var/www/errors

# Expose the port nginx is reachable on
EXPOSE 8080

# Let supervisord start nginx & php-fpm
CMD ["/usr/bin/supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]

# Configure a healthcheck to validate that everything is up&running
HEALTHCHECK --timeout=10s CMD curl --silent --fail http://127.0.0.1:8080/fpm-ping || exit 1